[package]
name = "dominoes"
version = "0.1.0"
edition = "2024_07"

[dev-dependencies]
cairo_test = "2.9.2"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html
